[workspace]
members = ["console_lib"]

[package]
name = "ConsoleSokoban"
version = "2.0.1"
edition = "2021"

[dependencies]
console_lib = { version = "0.1.0", path = "console_lib", features = ["custom_panic_hook"] }
